### ISSUE TITLE
Devise styles

### ISSUE THREAD

**Issue by timguoqk** [timguoqk/Academia-Course#6]
Pages generated by Devise (e.g. sign_in, sign_out, sign_up) require redesign.

**Comment by cassiuschen** [comment]
lalalalalalalala～

Cassius Chen, 2013

**Comment by cassiuschen** [comment]
你完成了这个i s su e？

Cassius Chen, 2013

**Comment by timguoqk** [comment]
语言对了，界面大部分凑活了……的样子？
（好吧现在感觉还差点）
